projects:
    app:
        schemaPath: src/schema.graphql
        extensions:
            endpoints:
                default: http://localhost:$SERVER_PORT
    database:
        schemaPath: src/generated/prisma-binding/prisma.graphql
        extensions:
            prisma: prisma/prisma.yml
            codegen:
                - generator: prisma-binding
                  language: typescript
                  output:
                      binding: src/generated/prisma-binding/index.ts
