version: 2
jobs:
  build:
    working_directory: ~/pyrog/server
    docker:
      - image: circleci/node:chakracore-10.13
    steps:
      - checkout:
          path: ~/pyrog
      - setup_remote_docker
      - run:
          name: Docker compose up pyrog
          command: env $(cat .env.staging) docker-compose up --build -d
      - run:
          name: Build and run docker container for tests
          command: |
            docker build -f Dockerfile.test --network server_default -t arkhn/pyrog_test:latest .
            PRISMA_ENDPOINT="http://prisma:4466" yarn run prisma deploy
            wget https://arkhn.org/pyrog_dev_static.zip
            unzip pyrog_dev_static.zip
            PRISMA_ENDPOINT="http://prisma:4466" yarn run prisma import --data ./static/pyrog_mimic_mapping.zip
            docker run --name test --network server_default arkhn/pyrog_test:latest
            docker cp test:/usr/src/app/coverage .
      - run:
          name: List docker containers
          command: docker ps -a
      - run:
          name: Find files
          command: find .
      - run:
          name: List files
          command: ls -alh
      - run:
          name: List files coverage
          command: ls coverage
      - store_artifacts:
          path: ./coverage
