version: 2
jobs:
  build:
    working_directory: ~/pyrog/server
    docker:
      - image: circleci/node:chakracore-10.13
    steps:
      - checkout:
          path: ~/pyrog
      - setup_remote_docker
      - run:
          name: Build docker images
          command: env $(cat .env.staging) docker-compose -f docker-compose.test.yml build
      - run:
          name: Run tests in docker
          command: env $(cat .env.staging) docker-compose -f docker-compose.test.yml up --exit-code-from test
      - run:
          name: Create symlink to coverage folder
          command: ln -s $(docker volume inspect -f '{{ .Mountpoint }}' server_coverage) coverage
      - run:
          name: File list coverage volume
          command: ls -alh $(docker volume inspect -f '{{ .Mountpoint }}' server_coverage)
      - run:
          name: List docker containers
          command: docker ps -a
      - run:
          name: List docker volumes
          command: docker volume ls
      - run:
          name: Find files
          command: find .
      - run:
          name: List files
          command: ls -alh
      - run:
          name: List files coverage
          command: ls coverage
      - store_artifacts:
          path: ./coverage
