version: 2
jobs:
  build:
    working_directory: ~/pyrog/server
    docker:
      - image: circleci/node:chakracore-10.13
    steps:
      - checkout:
          path: ~/pyrog
      - setup_remote_docker
      - run:
          name: Build docker images
          command: env $(cat .env.staging) docker-compose -f docker-compose.test.yml build
      - run:
          name: Run tests in docker
          command: env $(cat .env.staging) docker-compose -f docker-compose.test.yml up --exit-code-from test
      - run:
          name: Docker ps
          command: docker ps
      - run:
          name: Copy coverage metrics from docker container
          command: env $(cat .env.staging); docker cp server_test_1:$WORKDIR/coverage .
      - store_artifacts:
          path: coverage
