version: 2
jobs:
  build:
    working_directory: ~/pyrog
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: ls
          command: find .
      # - run:
      #     name: cd to server
      #     command: cd ./server
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      # - run:
      #     name: yarn install
      #     command: yarn install
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      #     paths:
      #       - ./node_modules
      # - run:
      #     name: yarn run test
      #     command: yarn run test
