version: 2
jobs:
  build:
    working_directory: ~/pyrog/server
    docker:
      - image: circleci/node:chakracore-10.13
    steps:
      - checkout:
          path: ~/pyrog
      - setup_remote_docker
      - run:
          name: Docker compose up pyrog
          command: env $(cat .env.staging) docker-compose up --build -d
      - run:
          name: Build and run docker container for tests
          command: |
            docker build -f Dockerfile.test --network server_default -t arkhn/pyrog_test:latest .
            docker run --name test --network server_default arkhn/pyrog_test:latest
            docker cp test:/usr/src/app/coverage .
      - store_artifacts:
          path: ./coverage
