version: 2
jobs:
  build:
    working_directory: ~/pyrog/server
    docker:
      - image: circleci/node:9.11.2
    steps:
      - checkout:
          path: ~/pyrog
      - run:
          name: pwd
          command: pwd
      - run:
          name: ls
          command: find .
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run yarn install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Start docker containers
          command: docker-compose up prisma
      - run:
          name: Reset static files
          command: |
            yarn run prisma deploy
            wget https://arkhn.org/pyrog_dev_static.zip
            unzip pyrog_dev_static.zip
            rm pyrog_dev_static.zip
            yarn run prisma import --data ./static/pyrog_mimic_mapping.zip
      - run:
          name: Run yarn run test
          command: yarn run test
